### ISSUE TITLE
Update Promotions

### ISSUE THREAD

**Issue by hrithik2200** [CSCI-GA-2820-SU24-001/promotions#5]
**As a** promotion manager  
 **I need** the ability to update the current promotions  
 **So that**  I can change the details of discounts and sales  
   
   
 ### Details and Assumptions
 * The promotions will be stored in a PostgreSQL database.
* Each promotion includes details like type (e.g., "Buy 1 Get 1 Free", "20% Off"), applicable products, and duration.
* Changes to promotions should be logged for audit purposes.
* Only authorized users can update promotions.
* Validation checks should ensure the promotion details are correct before updating (e.g., valid date ranges, correct product IDs).
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given there are multiple promotions in the database
 When I request to update the promotions
 Then I can modify the discounts information and the duration of the sales
 ```

**Comment by zimo1307** [comment]
**As a** promotion manager  
 **I need** the ability to update the current promotions  
 **So that**  I can change the details of discounts and sales  
   
 ### Details and Assumptions
 * The promotions will be stored in a PostgreSQL database.
* Each promotion includes details like type (e.g., "Buy 1 Get 1 Free", "20% Off"), applicable products, and duration.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given there are multiple promotions in the database
 When I request to update the promotions
 Then I can modify the discounts information and the duration of the sales
 ```

**Comment by anirudh28** [comment]
**As a** promotion manager  
 **I need** the ability to update the current promotions  
 **So that**  I can change the details of discounts and sales  
   
 ### Details and Assumptions
 * The promotions will be stored in a PostgreSQL database.
* Each promotion includes details like type (e.g., "Buy 1 Get 1 Free", "20% Off"), applicable products, and duration.
* Changes to promotions should be logged for audit purposes.
* Only authorized users can update promotions.
* Validation checks should ensure the promotion details are correct before updating (e.g., valid date ranges, correct product IDs).
* The system will provide a user-friendly interface to edit promotions.

 ### Acceptance Criteria  
   
 ```gherkin
 Given there are multiple promotions in the database
 When I request to update the promotions
 Then I can modify the discounts information and the duration of the sales
 ```
